import { getDb } from '@/db/client';
import { extractClientIp } from '@/auth/request-context';
import { fail, handle } from '@/lib/api-response';
import { consumeRateLimit, RateLimits } from '@/lib/rate-limit';
import { optOutOfReminders } from '@/services/reminder-optout';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/** Slugs are generated by `toSlug`; anything else can't address a real signup. */
const SLUG_RE = /^[a-z0-9-]{1,120}$/;

/**
 * Applies a reminder opt-out.
 *
 * POST rather than GET so that link scanners and mail-client prefetchers
 * cannot unsubscribe someone by merely following a link. It is also the target
 * of `List-Unsubscribe` / `List-Unsubscribe-Post: One-Click`, so a mail
 * provider may call it unattended — which is safe: the token authenticates the
 * request and the operation is idempotent.
 *
 * Two callers with different needs, separated by `Accept`: a provider reads
 * only the status code and ignores the body, while a person submitting the
 * confirm page must land on a page rather than a raw JSON envelope.
 */
export async function POST(request: Request) {
  const url = new URL(request.url);
  const form = await request.formData().catch(() => null);
  const wantsHtml = request.headers.get('accept')?.includes('text/html') ?? false;

  // The confirm page posts its own slug so we can send the person back to it
  // even when the opt-out fails and we never loaded the signup.
  const formSlug = String(form?.get('slug') ?? '');
  const fallbackSlug = SLUG_RE.test(formSlug) ? formSlug : null;

  const toPage = (slug: string, query: string) =>
    Response.redirect(new URL(`/s/${slug}/unsubscribe${query}`, url.origin), 303);

  return handle(async () => {
    const participantId = String(form?.get('p') ?? url.searchParams.get('p') ?? '');
    const token = String(form?.get('token') ?? url.searchParams.get('token') ?? '');

    try {
      const clientIp = extractClientIp(new Headers(request.headers));
      await consumeRateLimit(getDb(), RateLimits.reminderOptOutPerIp, clientIp ?? 'unknown');

      const result = await optOutOfReminders(getDb(), participantId, token);
      if (!result.ok) {
        if (wantsHtml && fallbackSlug) return toPage(fallbackSlug, '?error=1');
        return fail(result.error);
      }
      if (wantsHtml) return toPage(result.value.signupSlug, '?done=1');
      // One-click: the provider wants a bare success and ignores the body.
      return new Response(null, { status: 200 });
    } catch (err) {
      // Rate limiting throws. A machine caller should still see the JSON error
      // `handle` produces, but a person must not.
      if (wantsHtml && fallbackSlug) return toPage(fallbackSlug, '?error=1');
      throw err;
    }
  });
}
